### ISSUE TITLE
Finetuning & zero3 supported?

### ISSUE THREAD

**Issue by YasmineXXX** [boheumd/MA-LMM#1]
Thanks for sharing your great work! 

I would like to know if the model supports finetuning on your provided checkpoint for downstream tasks. Also, does it support deepspeed zero3?

**Comment by boheumd** [comment]
Hello, to finetune the model on downstream tasks, I recommend directly using the pre-trained weights from InstructBLIP. Since the provided checkpoints are the finetuned weights for each dataset, they may not have generalizable ability. Please check the latest README for more instruction.

And our code is based on the LAVIS, which does not support deepspeed zero3.
